### ISSUE TITLE
Approvazione del progetto

### ISSUE THREAD

**Issue by matteodv99tn** [matteodv99tn/TPA-homework1#1]
# Proposta di progetto

Buongiorno @DavidLeoni ,

io e @GabrieleBettini avremmo pensato di implementare un sistema manovella-pistone simile a quello mostrato negli esempi del documento con la consegna.

L'idea sarebbe di realizzare
-  una guida prismatica (@matteodv99tn )
-  la manovella con le rispettive aste di collegamento ( @GabrieleBettini )

Attualmente non sappiamo se ci saranno altre persone che vorranno integrarsi al nostro gruppo o che in caso vorranno interagire con i nostri devices.

**Domanda per la scrittura del programma:** è possibile utilizzare `struct` ausiliarie per agevolare la codifica?

In attesa di una sua risposta, distinti saluti.

Matteo Dalle Vedove

**Comment by DavidLeoni** [comment]
i device singoli vanno bene, però poi ognuno di voi dovrà fare una composizione (Machine) diversa,  in cui risulti che almeno un device venga istanziato n volte, quindi per es il sistema manovella-pistone andrebbe reso più complesso, che so, magari con n pistoni?

> Domanda per la scrittura del programma: è possibile utilizzare struct ausiliarie per agevolare la codifica?

certo

@GabrieleBettini

**Comment by matteodv99tn** [comment]
Ottimo, la ringrazio per il chiarimento, ci impegneremo a fare machine diverse istanziando più volte in maniera diversa i device.

@DavidLeoni @GabrieleBettini
